#!/usr/bin/bash
#
# Put customizations to your image in this file.

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any commands fail
set -o errexit

# Ensure we have updated standard packages
echo "* Updating standard packages.";
pkg_delete -v nodejs smtools
pkg_add -v nodejs smtools
npm install smartdc -g
npm install jsontool -g

# Configuring image specific packages
echo "* Configuring image specific packages.";
# Edit sudoers
if [ -f /opt/local/etc/sudoers ]; then
  cp /opt/local/etc/sudoers /opt/local/etc/sudoers.orig
  sed -e 's/^#root/root/g' < /opt/local/etc/sudoers.orig \
    > /opt/local/etc/sudoers
  rm /opt/local/etc/sudoers.orig
  echo 'admin ALL=(riak) NOPASSWD: /opt/local/sbin/riak*' >> /opt/local/etc/sudoers
  chmod 0440 /opt/local/etc/sudoers
fi

# Add placeholders to Riak config files
cd /opt/local/etc/riak
for I in vm.args app.config; do
  mv ${I} ${I}.orig
  sed -e "s/127.0.0.1/##PRIVATE_IP##/g" \
      -e "s/^-setcookie riak/-setcookie ##RIAK_SECRET##/g" \
      < ${I}.orig > ${I}
  chmod 0644 ${I}
  rm ${I}.orig
done

# Clean up
echo "* Cleaning up."
rm -rf /root/*

# Prepare image for provisioning
sm-prepare-image -y
